# values.yaml

name: mtl-argo-app
project: default
destination:
  namespace: default
  server: https://kubernetes.default.svc
source:
  path: 
  repoURL: https://github.com/argoproj/argocd-example-apps
  targetRevision: HEAD
automated:
  prune: true
  selfHeal: true
