# values.yaml

name: mtl-app

replicaCount: 1

image:
  repository: kowoatz/mtl-assignment
  tag: latest
  pullPolicy: IfNotPresent
  
containerPort: 8080

env:
  enabled: true
  env:
    FOO: 'BAR'

resources:
  enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 250Mi

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080
