###### Helm value for GO app.
name: mtl-app
replicaCount: 1
image:
  repository: kowoatz/mtl-assignment-3
  tag: latest
  pullPolicy: IfNotPresent
containerPort: 8080

env:
  enabled: false
  env:
    FOO: 'BAR'

resources:
  enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 250Mi

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

###### Helm value for ArgoCD.
appName: mtl-argocd-app
project: default
destination:
  namespace: default
  server: https://kubernetes.default.svc
source:
  path: ./manifest
  repoURL: https://github.com/anuchit17219/mtl-assaignment-ops.git
  targetRevision: HEAD
automated:
  prune: true
  selfHeal: true
