apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mtl-assignment-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ./manifest
    repoURL: 'https://github.com/anuchit17219/mtl-assaignment-ops.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true