name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  IMAGE_NAME: mtl-app
  IMAGE_TAG: latest
  HELM_PATH: helm/go-app
  MANIFEST_FOLDER: manifest
  MANIFEST_FILE: manifest.yaml
  MANIFEST_VALUES: values.yaml
  DEPLOY_VESION_FILE: deploy_version.txt
  GITOPS_REPO: anuchit17219/mtl-assingment-ops

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG .
    
    - name: Run image vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:$${{ env.IMAGE_TAG }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
    
    - name: Push Docker image
      run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    
    env:
      HELM_PATH: helm/go-app
      MANIFEST_FOLDER: manifest
      MANIFEST_FILE: manifest.yaml
      MANIFEST_VALUES: values.yaml
      DEPLOY_VESION_FILE: deploy_version.txt
      GITOPS_REPO: anuchit17219/mtl-assignment-ops
    
    steps:
    - uses: actions/checkout@v3
    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Generate K8S Manifest from Helm Chart
      run: |
        helm template mtl-chart $HELM_PATH > $MANIFEST_FILE -f $MANIFEST_VALUES
        cat $MANIFEST_FILE
    
    - name: Create manifest folder
      run: |
        mkdir $MANIFEST_FOLDER
        cp $MANIFEST_FILE $MANIFEST_FOLDER/$MANIFEST_FILE
    
    - name: Declare deploy version
      shell: bash
      run: |
        git rev-parse --short "$GITHUB_SHA" >> $MANIFEST_FOLDER/$DEPLOY_VESION_FILE
        echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
    
    - name: Pushes manifest file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITOPS }}
      with:
        source_file: '${{ env.MANIFEST_FOLDER }}'
        destination_repo: '${{ env.GITOPS_REPO }}'
        destination_folder: './'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        user_name: 'github-actions[bot]'
        commit_message: 'Deploy manifest version: ${{ env.SHA_SHORT }}'


