name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      IMAGE_NAME: mtl-app
      IMAGE_TAG: latest
      HELM_PATH: helm/go-app
      MANIFEST_FOLDER: manifest
      MANIFEST_FILE: manifest.yaml
      MANIFEST_VALUES: values.yaml
      DEPLOY_BRANCH: deployment

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t $DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG .
        docker push $DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
    
    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Generate K8S Manifest from Helm Chart
      run: |
        helm template mtl-chart $HELM_PATH > $MANIFEST_FOLDER/$MANIFEST_FILE -f $MANIFEST_FILE
        cat $MANIFEST_FOLDER/$MANIFEST_FILE

    - name: Deploy K8S manifest to Deployment branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: $DEPLOY_BRANCH
        FOLDER: $MANIFEST_FOLDER
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


